name: Deploy Node.js and Next.js App to Azure

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" # Adjust based on your app's requirement

      # Step 3: Install dependencies for backend and frontend
      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install
          cd ..

      # Step 4: Build Next.js frontend
      - name: Build Next.js Frontend
        run: |
          cd frontend
          npm run build
          cd ..

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "next-node-setup"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_67D5F9753CB140D38C04C0547805A556 }}
          package: .
