name: Deploy Node.js and Next.js to Azure

on:
  push:
    branches:
      - main # Replace with your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      # Step 3: Install and Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      # Step 4: Install Backend Dependencies
      - name: Install Backend
        run: |
          cd backend
          npm ci
          cd ..

      # Step 5: Deploy to Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "node-next-test"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CBC6C3868084B7797BA334A211355D5 }}
